declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';
  
  export interface LucideIconProps extends SVGProps<SVGSVGElement> {
    size?: number | string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
  }
  
  export type LucideIcon = FC<LucideIconProps>;
  
  // Export all icons as LucideIcon type
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const X: LucideIcon;
  export const Check: LucideIcon;
  export const Globe: LucideIcon;
  export const Briefcase: LucideIcon;
  export const Users: LucideIcon;
  export const Clock: LucideIcon;
  export const Users2: LucideIcon;
  export const Share2: LucideIcon;
  export const GraduationCap: LucideIcon;
  export const UserPlus: LucideIcon;
  export const BookOpen: LucideIcon;
  export const Heart: LucideIcon;
  export const Mail: LucideIcon;
  export const MapPin: LucideIcon;
  export const Phone: LucideIcon;
  export const Printer: LucideIcon;
  export const TriangleAlert: LucideIcon;
  export const Video: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const Loader2: LucideIcon;
  export const Star: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Calendar: LucideIcon;
  export const User: LucideIcon;
  export const Bell: LucideIcon;
  export const RefreshCcw: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const XCircle: LucideIcon;
  export const Edit2: LucideIcon;
  export const Save: LucideIcon;
  export const Trash2: LucideIcon;
  export const Play: LucideIcon;
  export const CreditCard: LucideIcon;
  export const UserCheck: LucideIcon;
  export const Search: LucideIcon;
  export const SlidersHorizontal: LucideIcon;
  export const Award: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Zap: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const Lock: LucideIcon;
  export const FileText: LucideIcon;
  export const Sparkles: LucideIcon;
  export const LayoutGrid: LucideIcon;
  export const LogOut: LucideIcon;
  export const Settings: LucideIcon;
  export const Upload: LucideIcon;
  export const Brain: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const Network: LucideIcon;
  export const Compass: LucideIcon;
  export const Layers: LucideIcon;
  export const Store: LucideIcon;
  export const Info: LucideIcon;
  export const Home: LucideIcon;
  export const ShoppingCart: LucideIcon;
  export const UserCircle2: LucideIcon;
  export const Menu: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const Brush: LucideIcon;
  export const Code: LucideIcon;
  export const Lightbulb: LucideIcon;
  export const DollarSign: LucideIcon;
  export const Megaphone: LucideIcon;
  export const Camera: LucideIcon;
  export const Database: LucideIcon;
  export const Dumbbell: LucideIcon;
  export const Music: LucideIcon;
  export const Headphones: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const CalendarDays: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const PenTool: LucideIcon;
  export const Send: LucideIcon;
  export const Clock3: LucideIcon;
  export const PlayCircle: LucideIcon;
  export const PencilLine: LucideIcon;
  export const BellRing: LucideIcon;
  export const Shield: LucideIcon;
  export const FileTextIcon: LucideIcon;
  export const BookOpenCheck: LucideIcon;
  export const List: LucideIcon;
  export const ClipboardList: LucideIcon;
  export const FolderTree: LucideIcon;
  export const UploadCloud: LucideIcon;
}